TutoringCenter/TutoringCenter/Models/Login.cs
// Login is where the data for the student is being stored.
// When the student checked in and out, the Student ID Number, and both the Reason and Subject IDs are stored here

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TutoringCenter.Models
{
    public class Login
    {
        // Constructor that initializes reasons and subjects
        public Login() {
            this.Reasons = new List<Reason>();
            this.ReasonIDs = new List<int>();
            this.Subjects = new List<Subject>();
            this.SubjectIDs = new List<int>();
        }
        // Primary Key
        public int ID { get; set; }

        // Checked in
        [DataType(DataType.DateTime)]
        public DateTime CheckedIn { get; set; }

        // Checked out
        public DateTime? CheckedOut { get; set; }

        // Interface collection of Reasons
        public virtual ICollection<Reason> Reasons { get; set; }

        // Interface collection of Subjects
        public virtual ICollection<Subject> Subjects { get; set; }

        //Student ID Number
        [Display(Name = "StudentID")]
        [Required(ErrorMessage ="Required")]
        public int RealStudentID { get; set; }

        // Foreign Key for StudentID
        [ForeignKey ("RealStudentID")] 
        public virtual Student Student { get; set; }

        // Reason IDs that are using ICollection
        [Required(ErrorMessage ="Required")]
        public List<int> ReasonIDs { get; set; }

        // Subject IDs that are using ICollection
        [Required(ErrorMessage ="Required")]
        public List<int> SubjectIDs { get; set; }
    }
}

TutoringCenter/TutoringCenter/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TutoringCenter.DAL;
using TutoringCenter.Models;

namespace TutoringCenter.Controllers
{
    public class LoginController : Controller
    {
        private ApplicationContext db = new ApplicationContext();

        // Login Page
        public ActionResult Index()
        {
            return View();
        }

        // Admin Page
        public ActionResult Admin()
        {
            return View();
        }

        // CheckedIn Page
        public ActionResult CheckedIn()
        {
            return View();
        }

        // CheckedOut Page
        public ActionResult CheckedOut()
        {
            return View();
        }

        // Login Page Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Login login)
        {
            TempData["TempStudentId"] = login.RealStudentID;
            int inputSID = (int)login.RealStudentID;

            // Admin use
            if(inputSID == 0)
            {
                return RedirectToAction("Admin");
            }


            int check = (from l in db.Logins
                         join s in db.Students
                            on l.Student.ID equals s.ID
                         where s.StudentID == inputSID && l.CheckedOut == null
                         select l).Count();

            Student student = db.Students.Where(x => x.StudentID == inputSID).FirstOrDefault();

            //STUDENT IS IN THE SYSTEM 
            if (student != null && check == 1)
            {  
                var students = db.Logins.Where(c => c.Student.StudentID == inputSID).Select(c => new { IDNUM = c.ID }).ToList().LastOrDefault();

                return RedirectToAction("Logout", new { id = students.IDNUM });              
            }
            //STUDENT IS NOT IN THE SYSTEM
            else
            {
                return RedirectToAction("Create");    
            }
        }

        // Create Page
        public ActionResult Create()
        {      
            ViewBag.data = TempData["TempStudentId"].ToString();
           

            var ReasonList = db.Reasons.Where(c => c.Status == false).ToList();
            var SubjectList = db.Subjects.Where(c => c.Status == false).ToList();

            ViewBag.Reasons = new MultiSelectList(ReasonList.ToList(), "R_ID", "Name");
            ViewBag.Subjects = new MultiSelectList(SubjectList.ToList(), "S_ID", "Name");
            return View(new Models.Login());
        }

        // Create Page Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Login login)
        {
            if (ModelState.IsValid)
            {
                Student student = db.Students.Where(x => x.StudentID == login.RealStudentID).FirstOrDefault();

                if(student != null)
                {
                    login.Student = student;
                    login.RealStudentID = student.ID;
                }
                else
                {
                    
                    student = new Student
                    {
                        StudentID = (int)login.RealStudentID
                    };
                    db.Students.Add(student);
                    login.RealStudentID = student.ID;
                }

                db.Logins.Add(login);
                db.SaveChanges();
                foreach(int ID in login.ReasonIDs)
                {
                    Reason reason = db.Reasons.Find(ID);
                    login.Reasons.Add(reason);
                }
                foreach (int ID in login.SubjectIDs)
                {
                    Subject subject = db.Subjects.Find(ID);
                    login.Subjects.Add(subject);
                   
                }
                db.Entry(login).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("CheckedIn");
            }
            return RedirectToAction("CheckedIn");
        }
    
        // Logout Page
        public ActionResult Logout(int? Id)
        {
          
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Login login = db.Logins.Find(Id);
            
            db.Logins
                .Where(y => y.Student.ID == login.RealStudentID)
                .ToList()
                .ForEach(a => a.CheckedOut = DateTime.Now);
            db.SaveChanges();
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }
    
        // Logout Page Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logout(Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;

                
                return RedirectToAction("CheckedOut");
            }
            return View(login);
        }

        // Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }    
    }
}

TutoringCenter/TutoringCenter/Controllers/ReasonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TutoringCenter.DAL;
using TutoringCenter.Models;

namespace TutoringCenter.Controllers
{
    public class ReasonsController : Controller
    {
        private ApplicationContext db = new ApplicationContext();

        // GET: Reasons
        public ActionResult Index()
        {
            return View(db.Reasons.ToList());
        }

        // GET: Reasons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reason reason = db.Reasons.Find(id);
            if (reason == null)
            {
                return HttpNotFound();
            }
            return View(reason);
        }

        // GET: Reasons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reasons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "R_ID,Name,Status")] Reason reason)
        {
            if (ModelState.IsValid)
            {
                db.Reasons.Add(reason);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reason);
        }

        // GET: Reasons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reason reason = db.Reasons.Find(id);
            if (reason == null)
            {
                return HttpNotFound();
            }
            return View(reason);
        }

        // POST: Reasons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "R_ID,Name,Status")] Reason reason)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reason).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reason);
        }

        // GET: Reasons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reason reason = db.Reasons.Find(id);
            if (reason == null)
            {
                return HttpNotFound();
            }
            return View(reason);
        }

        // POST: Reasons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reason reason = db.Reasons.Find(id);
            db.Reasons.Remove(reason);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TutoringCenter/TutoringCenter/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TutoringCenter.DAL;
using TutoringCenter.Models;

namespace TutoringCenter.Controllers
{
    public class SubjectsController : Controller
    {
        private ApplicationContext db = new ApplicationContext();

        // GET: Subjects
        public ActionResult Index()
        {
            return View(db.Subjects.ToList());
        }

        // GET: Subjects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // GET: Subjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "S_ID,Name,Status")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(subject);
        }

        // GET: Subjects/Edit/5
        public ActionResult Edit(int? id)
        {
            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "S_ID,Name,Status")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject subject = db.Subjects.Find(id);
            db.Subjects.Remove(subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TutoringCenter/TutoringCenter/Views/Login/Admin.cshtml
@*Admin page HTML*@

@{
    ViewBag.Title = "Admin";
}



<body>

    <div style="margin-left:auto;margin-right:auto;border-radius:20px;max-width:650px;border-color:white;background-color:white;
               padding-left:20px;padding-right:20px;padding-bottom:20px;padding-top:0;
               border:solid;border-width:2px;border-color:lightgray;box-shadow: 8px 8px 6px #888888 ;">

        <br />
        <center>
            <h3>Add/Update/Delete Reasons</h3>
            @Html.ActionLink("Click here to modify the Reasons", "Index", "Reasons")

            <br />
            <br />
            <h3>Add/Update/Delete Subjects</h3>
            @Html.ActionLink("Click here to modify the Subjects", "Index", "Subjects")

            <br />
            <br />
            <h3>Back to Home</h3>
            @Html.ActionLink("Click here to go back to the home page", "Index")

        </center>

    </div>
</body>
<br />

TutoringCenter/TutoringCenter/Views/Login/CheckedIn.cshtml
@* CheckedIn page HTML *@

@{
    ViewBag.Title = "CheckedIn";
}

<html style="" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tutoring Center</title>
    <link href="/Content/css?v=XrM_i-qL7ntkoyZchCNCLeeyZEN21k6m7X1mfUibzPs1" rel="stylesheet">


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

    </div>
    <div class="container body-content">

        <script type="text/JavaScript">
	        setTimeout("location.href = '/Login';", 1500);
        </script>

        <div style="margin-left:auto;margin-right:auto;border-radius:20px;max-width:650px;border-color:white;background-color:white;padding:20px;border:solid;border-width:2px;border-color:lightgray;box-shadow: 8px 8px 6px #888888 ;">

            <div class="form-horizontal">
                <table width="100%">
                    <tbody>
                        <tr>
                            <td width="75%">
                                <span style="font-size:32pt;">Welcome to the </span><br><span style="font-size:18pt;">Riverhawk Resource &amp; Tutoring Center</span>
                            </td>
                            <td width="25%">
                                <img src="~/Content/Images/Ricky.jpg" style="width:150px">
                            </td>
                        </tr>
                    </tbody>
                </table>
                <hr>
                <center>
                    <span style="color:lightseagreen;">
                        <h2>You are now checked in.</h2>
                    </span>
                </center>
            </div>
        </div>
        </div>
        <br />
</body>
</html>

TutoringCenter/TutoringCenter/Views/Login/CheckedOut.cshtml
@* CheckedOut Page HTML *@

@{
    ViewBag.Title = "CheckedOut";
}

<html style="" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tutoring Center</title>
    <link href="/Content/css?v=XrM_i-qL7ntkoyZchCNCLeeyZEN21k6m7X1mfUibzPs1" rel="stylesheet">

    <script src="/bundles/modernizr?v=inCVuEFe6J4Q07A0AcRsbJic_UE5MwpRMNGcOtk94TE1"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

    </div>
    <div class="container body-content">

        <script type="text/JavaScript">
            setTimeout("location.href = '/Login';", 1500);
        </script>

        <div style="margin-left:auto;margin-right:auto;border-radius:20px;max-width:650px;border-color:white;background-color:white;padding:20px;border:solid;border-width:2px;border-color:lightgray;box-shadow: 8px 8px 6px #888888 ;">

            <div class="form-horizontal">
                <table width="100%">
                    <tbody>
                        <tr>
                            <td width="75%">
                                <span style="font-size:32pt;">Welcome to the </span><br><span style="font-size:18pt;">Riverhawk Resource &amp; Tutoring Center</span>
                            </td>
                            <td width="25%">
                                <img src="~/Content/Images/Ricky.jpg" style="width:150px">
                            </td>
                        </tr>
                    </tbody>
                </table>
                <hr>
                    <center>
                        <span style="color:dodgerblue;">
                            <h2>You have successfully checked out. <br>Thank you for visiting!</h2>
                        </span>
                    </center>
                </div>
            </div>        
        </div>
    <br />
    </body>
</html>

TutoringCenter/TutoringCenter/Views/Login/Create.cshtml
@* Create Page HTML
    Where all data is inputted*@

@model TutoringCenter.Models.Login
@{
    ViewBag.Title = "Check In";
}

<script>
    $(document).ready(function () {

        $("#ReasonIDs").multiSelect();
        $("#SubjectIDs").multiSelect();
    })
</script>

<body>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <style>
                .Submit_Button {
                    background: rgb(28, 184, 65);
                    color: white;
                    border-radius: 20px;
                    padding-left: 50px;
                    padding-right: 50px;
                    padding-bottom: 15px;
                    padding-top: 15px;
                    font-size: 14pt;                    
                }

                    .Submit_Button:hover {
                        background-color: #808080;
                        color: white;
                    }

                input[type=number]::-webkit-inner-spin-button,
                input[type=number]::-webkit-outer-spin-button {
                    -webkit-appearance: none;
                    margin: 0;
                }

              
            </style>
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div style="margin-left:auto;margin-right:auto;border-radius:20px;max-width:650px;border-color:white;background-color:white;
                padding-left:20px;padding-right:20px;padding-bottom:20px;padding-top:0;
                border:solid;border-width:2px;border-color:lightgray;box-shadow: 8px 8px 6px #888888 ;">

                <table width="100%">
                    <tbody>
                        <tr>
                            <td width="75%">
                                <span style="font-size:32pt;">Welcome to the </span><br><span style="font-size:18pt;">Riverhawk Resource &amp; Tutoring Center</span>
                            </td>
                            <td width="25%">
                                <img src="~/Content/Images/Ricky.jpg" style="width:150px">
                            </td>
                        </tr>
                    </tbody>
                </table>




                <div class="form-group" style="display:none">

                    @Html.LabelFor(model => model.RealStudentID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.RealStudentID, new { htmlAttributes = new { @class = "form-control", @Value = @ViewBag.data } })
                       
                    </div>
                </div>

                <div class="form-group" style="display:none">

                    @Html.LabelFor(model => model.CheckedIn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.CheckedIn, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now } })
                       
                    </div>
                </div>
                <center>
                    <span style="font-weight:600; font-size:16pt">What are you using the Center for? Please select all that apply</span>
                </center>
                <div class="form-group" style="padding-left:17%">

                    <div class="col-md-12" >
                        @Html.ListBoxFor(model => model.ReasonIDs, ViewBag.Reasons as MultiSelectList, new { htmlAttributes = new { @class = "form-control", @Value = @ViewBag.data } })
                        @Html.ValidationMessageFor(model => model.ReasonIDs, "", new { @class = "text-danger" })
                    </div>
                </div>
                <center>
                    <span style="font-weight:600; font-size:16pt">Which subject are you using the Center for? </span>
                </center>
                <div class="form-group" style="padding-left:17%">
                    <div class="col-md-12">
                        @Html.ListBoxFor(model => model.SubjectIDs, ViewBag.Subjects as MultiSelectList, new { htmlAttributes = new { @class = "form-control", @Value = @ViewBag.data } })
                        @Html.ValidationMessageFor(model => model.SubjectIDs, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="text-align:center;">
                    <div class="col-md-offset-2 col-md-12">
                        <input type="submit" value="Check In" class="Submit_Button" />
                    </div>
                </div>
            </div>
        </div>
        <br />
    }

</body>

<script src="~/Scripts/jquery.multi-select.js" type="text/javascript"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TutoringCenter/TutoringCenter/Views/Login/Index.cshtml
@* Home Page HTML
    Where student ID is typed*@

@model TutoringCenter.Models.Login

@{
    ViewBag.Title = "Check In";
}

<body>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="container body-content">
            <style>
                .Submit_Button {
                    background: rgb(28, 184, 65);
                    color: white;
                    border-radius: 20px;
                    padding-left: 50px;
                    padding-right: 50px;
                    padding-bottom: 15px;
                    padding-top: 15px;
                    font-size: 14pt;
                }

                    .Submit_Button:hover {
                        background-color: #808080;
                        color: white;
                    }

                input[type=number]::-webkit-inner-spin-button,
                input[type=number]::-webkit-outer-spin-button {
                    -webkit-appearance: none;
                    margin: 0;
                }
            </style>

            <script>
                $(document).ready(function () {
                    $('#STUDENTID').focus()
                })
            </script>

            <br>
            <div style="margin-left:auto;margin-right:auto;border-radius:20px;max-width:650px;border-color:white;background-color:white;
               padding-left:20px;padding-right:20px;padding-bottom:20px;padding-top:0;
               border:solid;border-width:2px;border-color:lightgray;box-shadow: 8px 8px 6px #888888 ;">

                <table width="100%">
                    <tbody>
                        <tr>
                            <td width="75%">
                                <span style="font-size:32pt;">Welcome to the </span><br><span style="font-size:18pt;">Riverhawk Resource &amp; Tutoring Center</span>
                            </td>
                            <td width="25%">
                                <img src="/Content/Images/ricky.jpg" style="width:150px">
                            </td>
                        </tr>
                    </tbody>
                </table>
                <hr>
                <table width="100%">
                    <tbody>
                        <tr>
                            <td colspan="2">
                                <h3>Please Swipe your ID or Enter your WVUP ID below:</h3>
                            </td>
                        </tr>
                        <tr>
                            <td valign="top"></td>
                            <td>
                                <br>
                                <div class="editor-field">
                                    <center>
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">

                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.RealStudentID, new { htmlAttributes = new { @autofocus = "", @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.RealStudentID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </center>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <br><br>
                <center><input type="submit" value="Check In" class="Submit_Button"></center>

            </div>

        </div>
        <br>
        <br>
    }

</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}